name: Jalangi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jalangi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Jalangi
        run: npm install --save-dev jalangi2

      - name: Run Jalangi
        run: node node_modules/jalangi2/src/js/commands/jalangi.js --inlineIID --inlineSource --analysis jalangi_analysis/analysis.js jalangi_analysis/example.js

